spring:
  application:
    name: item-service

server:
  port: 8002

endpoints:
  products:
    base: "http://product-service/api/v1"

#No necesario por eureka porque viene implicito
#product-service:
    #  ribbon:
    #listOfServers: "localhost:8001/api/v1/products,localhost:9001/api/v1/products"

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"

#hystrix:
#  command:
#    default:
#      execution:
#        istolation:
#          thread:
#            timeoutOnMilliseconds: 20000
#
#ribbon:
#  ConnectTimeout: 3000
#  ReadTimeout: 10000