spring:
  application:
    name: item-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: "http://zipkin-server:9411/"
    sender:
      type: rabbit
  rabbitmq:
    host: rabbitmq38
server:
  port: 8002

endpoints:
  products:
    base: "http://product-service/api/v1"

#No necesario por eureka porque viene implicito
#product-service:
    #  ribbon:
    #listOfServers: "localhost:8001/api/v1/products,localhost:9001/api/v1/products"

eureka:
  client:
    service-url:
      defaultZone: "http://eureka-service:8761/eureka"

hystrix:
  command:
    default:
      execution:
        istolation:
          thread:
            timeoutOnMilliseconds: 60000

ribbon:
  ConnectTimeout: 9000
  ReadTimeout: 30000