spring:
  application:
    name: product-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: "http://localhost:9411/"
    sender:
      type: rabbit
  
  datasource:
    url: jdbc:mysql://mysql-server:3306/db_springboot_cloud?serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: Rla171290
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: INFO

#Selecciona puerto libre random
server:
  port: ${PORT:0}


eureka:
  client:
    service-url:
      defaultZone: "http://eureka-service:8761/eureka"
  #eureka instance para generar un valor de la app distinto por cada replica
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

