spring:
  application:
    name: user-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: "http://localhost:9411/"
  datasource:
    url: jdbc:postgresql://localhost:5432/db_springboot_cloud
    username: postgres
    password: Rla171290!!
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create


#Selecciona puerto libre random
server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG